"""Create initial project tables

Revision ID: xxxxxxxxxxxx
Revises: 
Create Date: 2025-07-17 21:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'xxxxxxxxxxxx' # O Alembic preenche isso automaticamente
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Criar tipos ENUM primeiro
    op.execute("""
    CREATE TYPE artist_status AS ENUM ('active', 'inactive');
    CREATE TYPE document_type AS ENUM ('technical_rider', 'hospitality_rider', 'press_kit');
    CREATE TYPE channel_type AS ENUM ('whatsapp', 'instagram_dm', 'telegram');
    CREATE TYPE conversation_status AS ENUM ('open', 'closed', 'needs_attention');
    CREATE TYPE message_sender_type AS ENUM ('user', 'agent');
    CREATE TYPE message_content_type AS ENUM ('text', 'image', 'audio', 'document');
    CREATE TYPE event_status AS ENUM ('pending_payment', 'confirmed', 'cancelled');
    """)

    # Criar tabelas
    op.execute("""
    CREATE TABLE artists (
        id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
        name VARCHAR(255) NOT NULL,
        photo_url TEXT,
        base_fee NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
        min_fee NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
        down_payment_percentage INT NOT NULL DEFAULT 50,
        base_city VARCHAR(255),
        status artist_status NOT NULL DEFAULT 'active',
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );
    """)
    op.execute("""
    CREATE TABLE contractors (
        id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
        name VARCHAR(255) NOT NULL,
        cpf_cnpj VARCHAR(18) UNIQUE,
        email VARCHAR(255),
        phone VARCHAR(20) UNIQUE NOT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );
    """)
    op.execute("""
    CREATE TABLE documents (
        id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
        artist_id UUID NOT NULL REFERENCES artists(id) ON DELETE CASCADE,
        document_type document_type NOT NULL,
        file_url TEXT NOT NULL,
        version INT NOT NULL DEFAULT 1,
        uploaded_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );
    """)
    op.execute("""
    CREATE TABLE conversations (
        id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
        contractor_id UUID NOT NULL REFERENCES contractors(id) ON DELETE CASCADE,
        channel channel_type NOT NULL,
        status conversation_status NOT NULL DEFAULT 'open',
        last_message_at TIMESTAMPTZ,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );
    """)
    op.execute("""
    CREATE TABLE messages (
        id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
        conversation_id UUID NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
        sender_type message_sender_type NOT NULL,
        content_type message_content_type NOT NULL,
        content TEXT NOT NULL,
        whatsapp_message_id VARCHAR(255) UNIQUE,
        timestamp TIMESTAMPTZ NOT NULL
    );
    """)
    op.execute("""
    CREATE TABLE events (
        id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
        artist_id UUID NOT NULL REFERENCES artists(id),
        contractor_id UUID NOT NULL REFERENCES contractors(id),
        title VARCHAR(255) NOT NULL,
        event_date DATE NOT NULL,
        event_location TEXT,
        agreed_fee NUMERIC(10, 2) NOT NULL,
        status event_status NOT NULL DEFAULT 'pending_payment',
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );
    """)
    op.execute("""
    CREATE TABLE agent_settings (
        id INT PRIMARY KEY DEFAULT 1,
        is_active BOOLEAN NOT NULL DEFAULT TRUE,
        buffer_seconds INT NOT NULL DEFAULT 5,
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        CONSTRAINT singleton CHECK (id = 1)
    );
    """)
    
    # Inserir a linha de configuração inicial
    op.execute("INSERT INTO agent_settings (id) VALUES (1);")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # A ordem de deleção é a reversa da criação para respeitar as constraints
    op.execute("DROP TABLE agent_settings;")
    op.execute("DROP TABLE events;")
    op.execute("DROP TABLE messages;")
    op.execute("DROP TABLE conversations;")
    op.execute("DROP TABLE documents;")
    op.execute("DROP TABLE contractors;")
    op.execute("DROP TABLE artists;")

    # Deletar os tipos ENUM
    op.execute("DROP TYPE event_status;")
    op.execute("DROP TYPE message_content_type;")
    op.execute("DROP TYPE message_sender_type;")
    op.execute("DROP TYPE conversation_status;")
    op.execute("DROP TYPE channel_type;")
    op.execute("DROP TYPE document_type;")
    op.execute("DROP TYPE artist_status;")

    # ### end Alembic commands ###